---
title: "Data"
format: html
editor: visual
---
```{r}
library(dplyr)
library(ggplot2)
library(tidyr)
```


## Seeds

```{r}
seed2023 <- read.csv("Raw Data/seedrates2023.csv")
#526 put out
seed2023 <- filter(seed2023, ending.weight != "disturbed")
seed2023 <- filter(seed2023, ending.weight != "broken")
seed2023 <- filter(seed2023, ending.weight != "was never put out")

seed2023 <- select(seed2023, 1:7)

seed2024 <- read.csv("Raw Data/seedsrates2024.csv")
seed2024 <- filter(seed2024, ending.weight != "disturbed")
seed2024 <- filter(seed2024, ending.weight != "not put out" & ending.weight != "never put out")
seed2024$Site <- gsub("yucca", "HOM", seed2024$Site)

seeds <- rbind(seed2023, seed2024)
seeds$ending.weight <- as.numeric(seeds$ending.weight)




unique(seeds$Size)
seeds$Size <- gsub(" ", "", seeds$Size)
seeds$Size <- gsub("medium", "med", seeds$Size)
seeds$Year <- as.factor(seeds$Year)
seedspring <- filter(seeds, Visit == "Spring")
seeds$Site <- gsub(" ", "", seeds$Site)

br <- read.csv("Raw Data/bromesites.csv")

seeds <- left_join(seeds, br, by = "Site")





ggplot(seeds, aes(Size, ending.weight)) + facet_grid(~ brome.x) + geom_boxplot() + ylab("Ending weight (g)") + theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank(),
panel.background = element_rect(colour = "black", size=1, fill = NA), axis.line = element_line(colour = "black"))


ggplot(seeds, aes(Microsite, ending.weight)) + geom_boxplot() 

ggplot(seeds, aes(as.factor(Year), ending.weight, color = Visit)) + geom_boxplot()

ggplot(seeds, aes(Site, ending.weight, color = Visit)) + geom_boxplot()

library(glmmTMB)
library(emmeans)
m1 <- glmmTMB(ending.weight ~  Size *brome.x  + (1|Site), data = seeds)
summary(m1)
car::Anova(m1)
emmeans(m1, pairwise ~ Size|brome.x)

m1 <- glmmTMB(ending.weight ~ Microsite +Year  + Visit + Size * brome.x+ (1|Site), data = seeds)
summary(m1)
car::Anova(m1)


m1 <- glmmTMB(ending.weight ~ Microsite  + Size * brome+ (1|Site) + (1|Year), data = seedspring)
summary(m1)
car::Anova(m1)

emmeans(m1, pairwise ~ Size)
shapiro.test(resid(m1))
plot(resid(m1))

```

# ants

```{r}
arth2 <- read.csv("Raw Data/pitfall_arth.csv")
ants <- dplyr::filter(arth2, Family == "Formicidae")
sum(ants$count)
sp <- ants %>% group_by(Genus, Species) %>% summarize(sum(count))

write.csv(ants, "Raw Data/ants_only.csv")

```


```{r}

bar <- filter(ants, site == "Barstow")


```


## Annuals

```{r}

plts <- read.csv("Raw Data/annuals/allplants_IDed.csv")
plts <- select(plts, -X)
plts <- select(plts, -6)
str(plts)



plt_wide <- plts %>% pivot_wider(names_from = species, values_from = abun)



unique(plt_wide$Year.NA)
unique(plt_wide$Rep.NA)
unique(plt_wide$Site)
unique(plt_wide$Microsite)

plt_wide$uniID <- paste(plt_wide$Site, plt_wide$Year.NA, plt_wide$Microsite, plt_wide$Rep.NA)
plt_wide$uniID <- gsub(" ", "", plt_wide$uniID)

plt_wide[is.na(plt_wide)] <- 0


env <- select(plt_wide, 1:5, uniID)
comm <- select(plt_wide, 6:91)


library(vegan)
richness <- specnumber(comm)
abun <- rowSums(comm)

env$rich <- richness
env$abun <- abun

#import plant metadata for zero rows
reps <- read.csv("Raw Data/reps.csv")
reps <- filter(reps, season == "spring")
reps$uniID <- paste(reps$Site, reps$year, reps$Microsite, reps$Rep)
reps$uniID <- gsub(" ", "", reps$uniID)
plt.ag <- left_join(reps, env, by = "uniID")

plt.ag$rich[is.na(plt.ag$rich)] <- 0
plt.ag$abun[is.na(plt.ag$abun)] <- 0


m1 <- glmmTMB(rich ~ Microsite.x * Site.x, family = "poisson", data = plt.ag)
summary(m1)
emmeans(Microsite.x~Site.x, m1)
emmeans(m1, pairwise ~ Microsite.x*Site.x)
```

## Simple plant viz
```{r}

ggplot(plt.ag, aes(Site.x, abun, fill = Microsite.x)) + geom_boxplot()
ggplot(plt.ag, aes(Site.x, rich, fill = Microsite.x, color = as.factor(year))) + geom_boxplot()
```